### ISSUE TITLE
Action failed

### ISSUE THREAD

**Issue by MontaEllis** [MLNLP-World/MyArxiv#6]
感谢大佬的项目，我部署的时候遇到了这个错误，不知道能不能解决？![](https://ellis.oss-cn-beijing.aliyuncs.com/img20230211152858.png)

**Comment by RRaymond-Yan** [comment]
Hi! Maybe you need to change the workflow permission settings.
<img width="617" alt="image" src="https://user-images.githubusercontent.com/48948973/219260579-4f33cd03-4c98-494c-9748-712f07676d7b.png">

**Comment by MontaEllis** [comment]
Thanks a lot!
